### ISSUE TITLE
error Failed at the chromely-react-app@1.0.0 build script.

### ISSUE THREAD

**Issue by forconz** [RupertAvery/Chromely.Mvc.Demos#6]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Tao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.14.5
3 info using node@v11.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle chromely-react-app@1.0.0~prebuild: chromely-react-app@1.0.0
6 info lifecycle chromely-react-app@1.0.0~build: chromely-react-app@1.0.0
7 verbose lifecycle chromely-react-app@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle chromely-react-app@1.0.0~build: PATH: C:\Users\Tao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Projects\LinkedIn\Chromely.Mvc.Demos-master\Chromely.Mvc.Demos-master\ChromelyMvcReactDemo\reactapp\node_modules\.bin;C:\Python36\Scripts\;C:\Python36\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Users\Tao\AppData\Local\Android\Sdk\tools;C:\Users\Tao\AppData\Local\Android\Sdk\platform-tools;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files\nodejs\;E:\Program Files\PuTTY\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\IncrediBuild;C:\Users\Tao\AppData\Local\Microsoft\WindowsApps;C:\Users\Tao\AppData\Local\Programs\Fiddler;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\Google\Chrome\Application\chrome.exe;C:\Users\Tao\AppData\Roaming\npm;C:\Users\Tao\.dotnet\tools;D:\Programs\Microsoft VS Code\bin
9 verbose lifecycle chromely-react-app@1.0.0~build: CWD: D:\Projects\LinkedIn\Chromely.Mvc.Demos-master\Chromely.Mvc.Demos-master\ChromelyMvcReactDemo\reactapp
10 silly lifecycle chromely-react-app@1.0.0~build: Args: [ '/d /s /c', 'webpack --mode development' ]
11 silly lifecycle chromely-react-app@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle chromely-react-app@1.0.0~build: Failed to exec build script
13 verbose stack Error: chromely-react-app@1.0.0 build: `webpack --mode development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Tao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Tao\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid chromely-react-app@1.0.0
15 verbose cwd D:\Projects\LinkedIn\Chromely.Mvc.Demos-master\Chromely.Mvc.Demos-master\ChromelyMvcReactDemo\reactapp
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Tao\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v11.9.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error chromely-react-app@1.0.0 build: `webpack --mode development`
22 error Exit status 1
23 error Failed at the chromely-react-app@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by forconz** [comment]
D:\Projects\LinkedIn\Chromely.Mvc.Demos-master\Chromely.Mvc.Demos-master\ChromelyMvcReactDemo\reactapp\node_modules\_webpack-cli@2.1.5@webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

  TypeError: Cannot read property 'properties' of undefined
      at module.exports (D:\Projects\LinkedIn\Chromely.Mvc.Demos-master\Chromely.Mvc.Demos-master\ChromelyMvcReactDemo\reactapp\node_modules\_webpack-cli@2.1.5@webpack-cli\bin\config-yargs.js:89:48)
      at D:\Projects\LinkedIn\Chromely.Mvc.Demos-master\Chromely.Mvc.Demos-master\ChromelyMvcReactDemo\reactapp\node_modules\_webpack-cli@2.1.5@webpack-cli\bin\webpack.js:60:27
      at Object.<anonymous> (D:\Projects\LinkedIn\Chromely.Mvc.Demos-master\Chromely.Mvc.Demos-master\ChromelyMvcReactDemo\reactapp\node_modules\_webpack-cli@2.1.5@webpack-cli\bin\webpack.js:515:3)
      at Module._compile (internal/modules/cjs/loader.js:734:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
      at Module.load (internal/modules/cjs/loader.js:626:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
      at Function.Module._load (internal/modules/cjs/loader.js:558:3)
      at Module.require (internal/modules/cjs/loader.js:663:17)
      at require (internal/modules/cjs/helpers.js:20:18)

**Comment by forconz** [comment]
![20181205152656522](https://user-images.githubusercontent.com/9990289/94413663-f701ea80-01ad-11eb-9cef-981a882488ce.png)

update \reactapp\package.json
    "webpack": "4.44.2",
    "webpack-cli": "3.3.12",
    "webpack-dev-server": "3.11.0"

delete the package-lock.json, and then install the babel-preset-stage-2:
npm install babel-preset-stage-2 --save-dev

The ChromelyMvcReactDemo project works ok for me.

![20200928173150](https://user-images.githubusercontent.com/9990289/94415752-8d371000-01b0-11eb-9179-e773d119e554.png)

![20200928173244](https://user-images.githubusercontent.com/9990289/94415815-a5a72a80-01b0-11eb-9534-c5806492ab19.png)
